#!/bin/sh
# Emit a TypeScript module with the raw bytes as a Uint8Array, plus
# the offset of each exported symbol within those bytes.
#
# Usage: emit_ts.sh <input.bin> <const-name> <output.ts> <input.dylib>
set -e
in=$1
name=$2
out=$3
dylib=$4

# Find the __text section's vaddr so we can convert nm addrs into blob
# offsets. otool prints addr as 0x...; convert via shell arithmetic.
text_vaddr_hex=$(otool -l "$dylib" | awk '
  $1 == "sectname" && $2 == "__text" { in_text = 1; next }
  in_text && $1 == "addr" { print $2; exit }
')
text_vaddr=$((text_vaddr_hex))

{
  echo "// Generated by extract_text.sh + emit_ts.sh from $in"
  echo "// Do not edit by hand; rerun \`make\` after editing the .S source."
  echo
  printf "export const %s = new Uint8Array([\n" "$name"
  xxd -i < "$in" | sed -E 's/^ +/  /'
  printf "]);\n\n"
  echo "export const SYMBOLS: Record<string, number> = {"
  nm -gU "$dylib" | while read addr type sym; do
    off=$(( 0x$addr - text_vaddr ))
    sym_nounderscore=${sym#_}
    printf "  %s: 0x%x,\n" "$sym_nounderscore" "$off"
  done
  echo "};"
} > "$out"
echo "emit_ts: wrote $(wc -c < "$out") bytes to $out"
